---
output: build/test

version: v0.2.0

data_pack:
  load:
    - src
  name: "[Test] {{ project_name | capitalize }} ({{ project_version }})"
  description: ''
  pack_format: 7

require:
  - mecha.contrib.scripting
  - mecha.contrib.messages

pipeline:
  - mecha
  - iredsc.counter
  - iredsc.message_format

meta:
  namespace:
    pack: "digs"
    messages: "messages"
